version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:3000"  # Ändra från 3000:3000 till 80:3000
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://98.128.179.210:5000
      - NODE_ENV=production

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/portfolio
      - PORT=5000

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: